//
//  ChainableFlag.swift
//  
//
//  Created by Ernest0N on 20.09.2020.
//

protocol ChainableFlag {}

extension Foundation.NSAttributedString: ChainableFlag {}
extension UIKit.NSDiffableDataSourceSectionSnapshot: ChainableFlag {}
extension UIKit.NSFileProviderExtension: ChainableFlag {}
extension UIKit.NSLayoutConstraint: ChainableFlag {}
extension UIKit.NSLayoutManager: ChainableFlag {}
extension UIKit.NSShadow: ChainableFlag {}
extension UIKit.NSTextAttachment: ChainableFlag {}
extension UIKit.NSTextContainer: ChainableFlag {}
extension UIKit.NSTextContentManager: ChainableFlag {}
extension UIKit.NSTextElement: ChainableFlag {}
extension UIKit.NSTextLayoutFragment: ChainableFlag {}
extension UIKit.NSTextLayoutManager: ChainableFlag {}
extension UIKit.NSTextLineFragment: ChainableFlag {}
extension UIKit.NSTextList: ChainableFlag {}
extension UIKit.NSTextSelection: ChainableFlag {}
extension UIKit.NSTextSelectionNavigation: ChainableFlag {}
extension UIKit.NSTextStorage: ChainableFlag {}
extension UIKit.NSTextViewportLayoutController: ChainableFlag {}
extension UIKit.UIActivity: ChainableFlag {}
extension UIKit.UIActivityIndicatorView: ChainableFlag {}
extension UIKit.UIActivityItemsConfiguration: ChainableFlag {}
extension UIKit.UIActivityItemsConfigurationReading: ChainableFlag {}
extension UIKit.UIActivityViewController: ChainableFlag {}
extension UIKit.UIAlertController: ChainableFlag {}
extension UIKit.UIAppearance: ChainableFlag {}
extension UIKit.UIApplication: ChainableFlag {}
extension UIKit.UIAttachmentBehavior: ChainableFlag {}
extension UIKit.UIBackgroundConfiguration: ChainableFlag {}
extension UIKit.UIBandSelectionInteraction: ChainableFlag {}
extension UIKit.UIBarAppearance: ChainableFlag {}
extension UIKit.UIBarButtonItem: ChainableFlag {}
extension UIKit.UIBarButtonItemAppearance: ChainableFlag {}
extension UIKit.UIBarButtonItemGroup: ChainableFlag {}
extension UIKit.UIBarItem: ChainableFlag {}
extension UIKit.UIBehavioralStyle: ChainableFlag {}
extension UIKit.UIBezierPath: ChainableFlag {}
extension UIKit.UIButton: ChainableFlag {}
extension UIKit.UICalendarView: ChainableFlag {}
extension UIKit.UICellAccessory: ChainableFlag {}
extension UIKit.UICellConfigurationState: ChainableFlag {}
extension UIKit.UICloudSharingController: ChainableFlag {}
extension UIKit.UICollectionView: ChainableFlag {}
extension UIKit.UICollectionViewCell: ChainableFlag {}
extension UIKit.UICollectionViewCompositionalLayout: ChainableFlag {}
extension UIKit.UICollectionViewFlowLayout: ChainableFlag {}
extension UIKit.UICollectionViewLayout: ChainableFlag {}
extension UIKit.UICollectionViewListCell: ChainableFlag {}
extension UIKit.UICollectionViewTransitionLayout: ChainableFlag {}
extension UIKit.UICollisionBehavior: ChainableFlag {}
extension UIKit.UIColor: ChainableFlag {}
extension UIKit.UIColorPickerViewController: ChainableFlag {}
extension UIKit.UIColorWell: ChainableFlag {}
extension UIKit.UIConfigurationColorTransformer: ChainableFlag {}
extension UIKit.UIConfigurationState: ChainableFlag {}
extension UIKit.UIContentConfiguration: ChainableFlag {}
extension UIKit.UIContextMenuConfiguration: ChainableFlag {}
extension UIKit.UIContextualAction: ChainableFlag {}
extension UIKit.UIControl: ChainableFlag {}
extension UIKit.UIDatePicker: ChainableFlag {}
extension UIKit.UIDevice: ChainableFlag {}
extension UIKit.UIDragItem: ChainableFlag {}
extension UIKit.UIDragSession: ChainableFlag {}
extension UIKit.UIDropInteraction: ChainableFlag {}
extension UIKit.UIFeedbackGenerator: ChainableFlag {}
extension UIKit.UIFieldBehavior: ChainableFlag {}
extension UIKit.UIGestureRecognizer: ChainableFlag {}
extension UIKit.UIGraphicsPDFRenderer: ChainableFlag {}
extension UIKit.UIGravityBehavior: ChainableFlag {}
extension UIKit.UIImage: ChainableFlag {}
extension UIKit.UIImagePickerController: ChainableFlag {}
extension UIKit.UIImageView: ChainableFlag {}
extension UIKit.UIImpactFeedbackGenerator: ChainableFlag {}
extension UIKit.UIIndirectScribbleInteraction: ChainableFlag {}
extension UIKit.UIInputView: ChainableFlag {}
extension UIKit.UIInputViewController: ChainableFlag {}
extension UIKit.UILabel: ChainableFlag {}
extension UIKit.UILayoutGuide: ChainableFlag {}
extension UIKit.UIListContentConfiguration: ChainableFlag {}
extension UIKit.UIListSeparatorConfiguration: ChainableFlag {}
extension UIKit.UILongPressGestureRecognizer: ChainableFlag {}
extension UIKit.UIManagedDocument: ChainableFlag {}
extension UIKit.UIMenu: ChainableFlag {}
extension UIKit.UIMenuBuilder: ChainableFlag {}
extension UIKit.UIMenuController: ChainableFlag {}
extension UIKit.UIMenuElement: ChainableFlag {}
extension UIKit.UIMenuLeaf: ChainableFlag {}
extension UIKit.UIMenuSystem: ChainableFlag {}
extension UIKit.UINavigationBar: ChainableFlag {}
extension UIKit.UINavigationBarAppearance: ChainableFlag {}
extension UIKit.UINavigationController: ChainableFlag {}
extension UIKit.UINavigationItem: ChainableFlag {}
extension UIKit.UINotificationFeedbackGenerator: ChainableFlag {}
extension UIKit.UIPageControl: ChainableFlag {}
extension UIKit.UIPageViewController: ChainableFlag {}
extension UIKit.UIPanGestureRecognizer: ChainableFlag {}
extension UIKit.UIPasteboard: ChainableFlag {}
extension UIKit.UIPasteConfiguration: ChainableFlag {}
extension UIKit.UIPasteControl: ChainableFlag {}
extension UIKit.UIPencilInteraction: ChainableFlag {}
extension UIKit.UIPickerView: ChainableFlag {}
extension UIKit.UIPinchGestureRecognizer: ChainableFlag {}
extension UIKit.UIPointerAccessory: ChainableFlag {}
extension UIKit.UIPointerInteraction: ChainableFlag {}
extension UIKit.UIPointerRegion: ChainableFlag {}
extension UIKit.UIPointerStyle: ChainableFlag {}
extension UIKit.UIPopoverBackgroundView: ChainableFlag {}
extension UIKit.UIPopoverPresentationController: ChainableFlag {}
extension UIKit.UIPopoverPresentationControllerSourceItem: ChainableFlag {}
extension UIKit.UIPresentationController: ChainableFlag {}
extension UIKit.UIPreviewInteraction: ChainableFlag {}
extension UIKit.UIPreviewParameters: ChainableFlag {}
extension UIKit.UIPrinter: ChainableFlag {}
extension UIKit.UIPrinterPickerController: ChainableFlag {}
extension UIKit.UIPrintError: ChainableFlag {}
extension UIKit.UIPrintFormatter: ChainableFlag {}
extension UIKit.UIPrintInfo: ChainableFlag {}
extension UIKit.UIPrintInteractionController: ChainableFlag {}
extension UIKit.UIPrintPageRenderer: ChainableFlag {}
extension UIKit.UIProgressView: ChainableFlag {}
extension UIKit.UIPushBehavior: ChainableFlag {}
extension UIKit.UIRefreshControl: ChainableFlag {}
extension UIKit.UIRotationGestureRecognizer: ChainableFlag {}
extension UIKit.UIScene: ChainableFlag {}
extension UIKit.UISceneSession: ChainableFlag {}
extension UIKit.UIScreen: ChainableFlag {}
extension UIKit.UIScreenshotService: ChainableFlag {}
extension UIKit.UIScrollView: ChainableFlag {}
extension UIKit.UISearchBar: ChainableFlag {}
extension UIKit.UISearchController: ChainableFlag {}
extension UIKit.UISearchSuggestion: ChainableFlag {}
extension UIKit.UISearchTextField: ChainableFlag {}
extension UIKit.UISegmentedControl: ChainableFlag {}
extension UIKit.UISelectionFeedbackGenerator: ChainableFlag {}
extension UIKit.UISheetPresentationController: ChainableFlag {}
extension UIKit.UISlider: ChainableFlag {}
extension UIKit.UISnapBehavior: ChainableFlag {}
extension UIKit.UISplitViewController: ChainableFlag {}
extension UIKit.UIStackView: ChainableFlag {}
extension UIKit.UIStepper: ChainableFlag {}
extension UIKit.UISwipeActionsConfiguration: ChainableFlag {}
extension UIKit.UISwipeGestureRecognizer: ChainableFlag {}
extension UIKit.UISwitch: ChainableFlag {}
extension UIKit.UITabBar: ChainableFlag {}
extension UIKit.UITabBarAppearance: ChainableFlag {}
extension UIKit.UITabBarController: ChainableFlag {}
extension UIKit.UITabBarItem: ChainableFlag {}
extension UIKit.UITableView: ChainableFlag {}
extension UIKit.UITableViewCell: ChainableFlag {}
extension UIKit.UITableViewController: ChainableFlag {}
extension UIKit.UITableViewHeaderFooterView: ChainableFlag {}
extension UIKit.UITapGestureRecognizer: ChainableFlag {}
extension UIKit.UITextChecker: ChainableFlag {}
extension UIKit.UITextDragPreviewRenderer: ChainableFlag {}
extension UIKit.UITextDropProposal: ChainableFlag {}
extension UIKit.UITextField: ChainableFlag {}
extension UIKit.UITextFormattingCoordinator: ChainableFlag {}
extension UIKit.UITextInput: ChainableFlag {}
extension UIKit.UITextInputTraits: ChainableFlag {}
extension UIKit.UITextInteraction: ChainableFlag {}
extension UIKit.UITextItemInteraction: ChainableFlag {}
extension UIKit.UITextPasteConfigurationSupporting: ChainableFlag {}
extension UIKit.UITextPasteDelegate: ChainableFlag {}
extension UIKit.UITextSearching: ChainableFlag {}
extension UIKit.UITextView: ChainableFlag {}
extension UIKit.UITimingCurveProvider: ChainableFlag {}
extension UIKit.UIToolbar: ChainableFlag {}
extension UIKit.UIToolbarAppearance: ChainableFlag {}
extension UIKit.UIToolTipInteraction: ChainableFlag {}
extension UIKit.UITrackingLayoutGuide: ChainableFlag {}
extension UIKit.UITraitCollection: ChainableFlag {}
extension UIKit.UIVideoEditorController: ChainableFlag {}
extension UIKit.UIView: ChainableFlag {}
extension UIKit.UIViewAnimating: ChainableFlag {}
extension UIKit.UIViewConfigurationState: ChainableFlag {}
extension UIKit.UIViewController: ChainableFlag {}
extension UIKit.UIViewControllerTransitionCoordinator: ChainableFlag {}
extension UIKit.UIViewPropertyAnimator: ChainableFlag {}
extension UIKit.UIWebView: ChainableFlag {}
extension UIKit.UIWindow: ChainableFlag {}
extension UIKit.UIWindowScene: ChainableFlag {}
extension UIKit.UISearchToken: ChainableFlag {}
extension WebKit.WKWebView: ChainableFlag {}
extension Foundation.NSData: ChainableFlag {}
extension Foundation.NSArray: ChainableFlag {}
extension Foundation.NSDictionary: ChainableFlag {}
extension QuartzCore.CALayer: ChainableFlag {}
extension UIKit.UICollectionViewFlowLayout: ChainableFlag {}
extension WebKit.WKWebViewConfiguration: ChainableFlag {}
extension AVFoundation.AVPlayer: ChainableFlag {}
// extension MapKit.MKMapView: ChainableFlag {}
