//
//  NeedChainable.swift
//  
//
//  Created by Ernest0N on 20.09.2020.
//

// This protocol use to filter out all classes that can be chained
protocol NeedChainable {}

extension UIKit.UIButton: NeedChainable {}
extension UIKit.UIImageView: NeedChainable {}
extension UIKit.UILabel: NeedChainable {}
extension UIKit.UITableView: NeedChainable {}
extension UIKit.UITableViewCell: NeedChainable {}
extension UIKit.UITableViewController: NeedChainable {}
extension UIKit.UITableViewHeaderFooterView: NeedChainable {}
extension UIKit.UITapGestureRecognizer: NeedChainable {}
extension UIKit.UISwipeActionsConfiguration: NeedChainable {}
extension UIKit.UISwipeGestureRecognizer: NeedChainable {}
extension UIKit.UIRotationGestureRecognizer: NeedChainable {}
extension UIKit.UIPanGestureRecognizer: NeedChainable {}
extension UIKit.UIPinchGestureRecognizer: NeedChainable {}
extension UIKit.UIGestureRecognizer: NeedChainable {}
extension UIKit.UILongPressGestureRecognizer: NeedChainable {}
extension UIKit.UICollectionView: NeedChainable {}
extension UIKit.UICollectionViewFlowLayout: NeedChainable {}
extension UIKit.UICollectionViewLayout: NeedChainable {}
extension UIKit.UIScrollView: NeedChainable {}
extension UIKit.UISlider: NeedChainable {}
extension UIKit.UIStackView: NeedChainable {}
extension UIKit.UIStepper: NeedChainable {}
extension UIKit.UISwitch: NeedChainable {}
extension UIKit.UITextView: NeedChainable {}
extension UIKit.UIBezierPath: NeedChainable {}
extension UIKit.UIControl: NeedChainable {}
extension UIKit.UISegmentedControl: NeedChainable {}
extension UIKit.UIView: NeedChainable {}
extension UIKit.UIToolbar: NeedChainable {}
extension UIKit.UITabBar: NeedChainable {}
extension UIKit.UITabBarAppearance: NeedChainable {}
extension UIKit.UITabBarController: NeedChainable {}
extension UIKit.UITabBarItem: NeedChainable {}
extension UIKit.UIDatePicker: NeedChainable {}
extension UIKit.UIProgressView: NeedChainable {}
extension UIKit.UISearchBar: NeedChainable {}
extension Foundation.NSAttributedString: NeedChainable {}
extension QuartzCore.CALayer: NeedChainable {}
extension QuartzCore.CAShapeLayer: NeedChainable {}
extension QuartzCore.CAGradientLayer: NeedChainable {}
extension WebKit.WKWebView: NeedChainable {}
extension WebKit.WKWebViewConfiguration: NeedChainable {}
extension AVFoundation.AVPlayer: NeedChainable {}
extension UIKit.NSFileProviderExtension: NeedChainable {}
extension UIKit.NSLayoutConstraint: NeedChainable {}
extension UIKit.NSLayoutManager: NeedChainable {}
extension UIKit.NSShadow: NeedChainable {}
extension UIKit.NSTextAttachment: NeedChainable {}
extension UIKit.NSTextContainer: NeedChainable {}
extension UIKit.NSTextContentManager: NeedChainable {}
extension UIKit.NSTextLayoutManager: NeedChainable {}
extension UIKit.NSTextSelection: NeedChainable {}
extension UIKit.NSTextSelectionNavigation: NeedChainable {}
extension UIKit.NSTextStorage: NeedChainable {}
extension UIKit.NSTextViewportLayoutController: NeedChainable {}
extension UIKit.UIActivity: NeedChainable {}
extension UIKit.UIActivityItemsConfiguration: NeedChainable {}
extension UIKit.UIActivityItemsConfigurationReading: NeedChainable {}
extension UIKit.UIActivityViewController: NeedChainable {}
extension UIKit.UIAlertController: NeedChainable {}
extension UIKit.UIAppearance: NeedChainable {}
extension UIKit.UIApplication: NeedChainable {}
extension UIKit.UIAttachmentBehavior: NeedChainable {}
extension UIKit.UIBackgroundConfiguration: NeedChainable {}
extension UIKit.UIBandSelectionInteraction: NeedChainable {}
extension UIKit.UIBarAppearance: NeedChainable {}
extension UIKit.UIBarButtonItem: NeedChainable {}
extension UIKit.UIBarButtonItemAppearance: NeedChainable {}
extension UIKit.UIBarButtonItemGroup: NeedChainable {}
extension UIKit.UIBarItem: NeedChainable {}
extension UIKit.UIBehavioralStyle: NeedChainable {}
extension UIKit.UICalendarView: NeedChainable {}
extension UIKit.UICellAccessory: NeedChainable {}
extension UIKit.UICellConfigurationState: NeedChainable {}
extension UIKit.UICloudSharingController: NeedChainable {}
extension UIKit.UICollectionViewListCell: NeedChainable {}
extension UIKit.UICollectionViewTransitionLayout: NeedChainable {}
extension UIKit.UICollisionBehavior: NeedChainable {}
extension UIKit.UIColor: NeedChainable {}
extension UIKit.UIColorPickerViewController: NeedChainable {}
extension UIKit.UIColorWell: NeedChainable {}
extension UIKit.UIConfigurationColorTransformer: NeedChainable {}
extension UIKit.UIConfigurationState: NeedChainable {}
extension UIKit.UIContentConfiguration: NeedChainable {}
extension UIKit.UIContextMenuConfiguration: NeedChainable {}
extension UIKit.UIContextualAction: NeedChainable {}
extension UIKit.UIDevice: NeedChainable {}
extension UIKit.UIDragItem: NeedChainable {}
extension UIKit.UIDragSession: NeedChainable {}
extension UIKit.UIDropInteraction: NeedChainable {}
extension UIKit.UIFeedbackGenerator: NeedChainable {}
extension UIKit.UIFieldBehavior: NeedChainable {}
extension UIKit.UIGraphicsPDFRenderer: NeedChainable {}
extension UIKit.UIGravityBehavior: NeedChainable {}
extension UIKit.UIImagePickerController: NeedChainable {}
extension UIKit.UIImpactFeedbackGenerator: NeedChainable {}
extension UIKit.UIIndirectScribbleInteraction: NeedChainable {}
extension UIKit.UIInputView: NeedChainable {}
extension UIKit.UIInputViewController: NeedChainable {}
extension UIKit.UILayoutGuide: NeedChainable {}
extension UIKit.UIManagedDocument: NeedChainable {}
extension UIKit.UIMenu: NeedChainable {}
extension UIKit.UIMenuBuilder: NeedChainable {}
extension UIKit.UIMenuController: NeedChainable {}
extension UIKit.UIMenuElement: NeedChainable {}
extension UIKit.UIMenuLeaf: NeedChainable {}
extension UIKit.UIMenuSystem: NeedChainable {}
extension UIKit.UINavigationBar: NeedChainable {}
extension UIKit.UINavigationBarAppearance: NeedChainable {}
extension UIKit.UINavigationController: NeedChainable {}
extension UIKit.UINavigationItem: NeedChainable {}
extension UIKit.UINotificationFeedbackGenerator: NeedChainable {}
extension UIKit.UIPageViewController: NeedChainable {}
extension UIKit.UIPasteboard: NeedChainable {}
extension UIKit.UIPasteConfiguration: NeedChainable {}
extension UIKit.UIPasteControl: NeedChainable {}
extension UIKit.UIPencilInteraction: NeedChainable {}
extension UIKit.UIPointerAccessory: NeedChainable {}
extension UIKit.UIPointerInteraction: NeedChainable {}
extension UIKit.UIPointerRegion: NeedChainable {}
extension UIKit.UIPointerStyle: NeedChainable {}
extension UIKit.UIPopoverBackgroundView: NeedChainable {}
extension UIKit.UIPopoverPresentationController: NeedChainable {}
extension UIKit.UIPopoverPresentationControllerSourceItem: NeedChainable {}
extension UIKit.UIPresentationController: NeedChainable {}
extension UIKit.UIPreviewInteraction: NeedChainable {}
extension UIKit.UIPreviewParameters: NeedChainable {}
extension UIKit.UIPrinterPickerController: NeedChainable {}
extension UIKit.UIPrintFormatter: NeedChainable {}
extension UIKit.UIPrintInfo: NeedChainable {}
extension UIKit.UIPrintPageRenderer: NeedChainable {}
extension UIKit.UIPushBehavior: NeedChainable {}
extension UIKit.UIRefreshControl: NeedChainable {}
extension UIKit.UIScene: NeedChainable {}
extension UIKit.UISceneSession: NeedChainable {}
extension UIKit.UIScreen: NeedChainable {}
extension UIKit.UISearchTextField: NeedChainable {}
extension UIKit.UISheetPresentationController: NeedChainable {}
extension UIKit.UISnapBehavior: NeedChainable {}
extension UIKit.UISplitViewController: NeedChainable {}
extension UIKit.UIToolbarAppearance: NeedChainable {}
extension UIKit.UIToolTipInteraction: NeedChainable {}
extension UIKit.UITrackingLayoutGuide: NeedChainable {}
extension UIKit.UIVideoEditorController: NeedChainable {}
extension UIKit.UIViewPropertyAnimator: NeedChainable {}
extension UIKit.UIWebView: NeedChainable {}
extension UIKit.UIWindow: NeedChainable {}
extension UIKit.UIWindowScene: NeedChainable {}